/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminProductPanels;

import DataPackage.Product;
import UsersPackage.Admin;
import java.util.ArrayList;
import javax.swing.event.TableModelEvent;
import javax.swing.plaf.PanelUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kimoo
 */
public class ProductTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductTablePanel
     */
    public ProductTablePanel() {
        initComponents();
//        addDataToTable();

    }

//    public void showPanel() {
//        this.setVisible(true);
////        this.removeAll();
////            this.jTable1.removeAll();
//                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//                    if (model.getRowCount() > 0) {
//     for (int i = model.getRowCount() - 1; i > -1; i--) {
//         model.removeRow(i);
//     }
// }
//                    addDataToTable();
////                        model.fireTableDataChanged();
////        addDataToTable();
//
//    }
   

    public void hidePanel() {
        this.setVisible(false);
//        addDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Id", "category", "Production Date", "Expiration Date", "purchasing Price", "Selling Price", "Available quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
     

    @Override
    public void setUI(PanelUI pui) {
        super.setUI(pui); //To change body of generated methods, choose Tools | Templates.
        
    }

    @Override
    public void updateUI() {
        super.updateUI(); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
